title: Selemani Lusukama
description: Freelance Software Developer, Microsoft Certified Trainer, Cloud Migration Consultant, and MICT SETA Assessor and Moderator.
lang: en-ZA
timezone: Africa/Johannesburg
